rm(list=ls()); par(pch=20)

library(ade4)
library(PLNmodels)
data("aravo")

Y = as.matrix(aravo$spe); head(Y); dim(Y)
X = aravo$env; head(X); dim(X); plot(X)
n = nrow(Y); p = ncol(Y)

####################################################################
# PCA
logY = log(1+Y)
PCA = prcomp(logY, scale = TRUE)
print(PCA)
plot(PCA)
summary(PCA)
# pdf('Fig-PCA-aravo-inertia.pdf')
plot(0:min(n, p), c(0, cumsum(PCA$sdev^2))/p, type='b', main='', ylab='', xlab='', pch=20)
# dev.off()
# pdf('Fig-PCA-aravo-biplot.pdf')
biplot(PCA); abline(h=0, v=0, lty=2)
# dev.off()

####################################################################
# PLNPCA
Q.list = (1:round(2*sqrt(p)))
PLNPCA.raw = PLNPCA(Y ~ 1, Q=Q.list)
save(PLNPCA.raw, file='aravo-PLNPCA.raw.Rdata')
load('aravo-PLNPCA.raw.Rdata')
# pdf('Fig-PLNPCA.raw-aravo-modsel.pdf')
PLNPCA.raw$plot()
# dev.off()
bestPLNPCA.raw = PLNPCA.raw$getModel(which.max(PLNPCA.raw$criteria$R2))
# pdf('Fig-PLNPCA.raw-aravo-invPC1-2.pdf')
bestPLNPCA.raw$plot_individual.map(axes=c(1,2), col=as.numeric(as.factor(X$ZoogD)))
# dev.off()
# pdf('Fig-PLNPCA.raw-aravo-invPC3-4.pdf')
bestPLNPCA.raw$plot_individual.map(axes=c(3,4), col=as.numeric(as.factor(X$ZoogD)))
# dev.off()
# pdf('Fig-PLNPCA.raw-aravo-corPC1-2.pdf')
bestPLNPCA.raw$plot_correlation.circle(axes=c(1,2))
# dev.off()
# pdf('Fig-PLNPCA.raw-aravo-corPC3-4.pdf')
bestPLNPCA.raw$plot_correlation.circle(axes=c(3,4))
# dev.off()

####################################################################
# PLNPCA + offset
O = outer(log(rowSums(Y)), rep(1, p))
PLNPCA.offset = PLNPCA(Y ~ 1 + offset(O), Q=Q.list)
save(PLNPCA.offset, file='aravo-PLNPCA.offset.Rdata')
load('aravo-PLNPCA.offset.Rdata')
# pdf('Fig-PLNPCA.offset-aravo-modsel.pdf')
PLNPCA.offset$plot()
# dev.off()
bestPLNPCA.offset = PLNPCA.offset$getModel(which.max(PLNPCA.offset$criteria$R2))
# pdf('Fig-PLNPCA.offset-aravo-invPC1-2.pdf')
bestPLNPCA.offset$plot_individual.map(axes=c(1,2), col=as.numeric(as.factor(X$ZoogD)))
# dev.off()
# pdf('Fig-PLNPCA.offset-aravo-invPC3-4.pdf')
bestPLNPCA.offset$plot_individual.map(axes=c(3,4), col=as.numeric(as.factor(X$ZoogD)))
# dev.off()
# pdf('Fig-PLNPCA.offset-aravo-corPC1-2.pdf')
bestPLNPCA.offset$plot_correlation.circle(axes=c(1,2))
# dev.off()
# pdf('Fig-PLNPCA.offset-aravo-corPC3-4.pdf')
bestPLNPCA.offset$plot_correlation.circle(axes=c(3,4))
# dev.off()

####################################################################
# PLNPCA + cov
# PLNPCA.cov = PLNPCA(Y ~ X, Q=Q.list)
PLNPCA.cov = PLNPCA(Y ~ 1 + X$Aspect + X$Slope + X$Form + X$PhysD + X$ZoogD + X$Snow, Q=Q.list)
save(PLNPCA.cov, file='aravo-PLNPCA.cov.Rdata')
load('aravo-PLNPCA.cov.Rdata')
# pdf('Fig-PLNPCA.cov-aravo-modsel.pdf')
PLNPCA.cov$plot()
# dev.off()
bestPLNPCA.cov = PLNPCA.cov$getModel(which.max(PLNPCA.cov$criteria$R2))
# pdf('Fig-PLNPCA.cov-aravo-invPC1-2.pdf')
bestPLNPCA.cov$plot_individual.map(axes=c(1,2), col=as.numeric(as.factor(X$ZoogD)))
# dev.off()
# pdf('Fig-PLNPCA.cov-aravo-invPC3-4.pdf')
bestPLNPCA.cov$plot_individual.map(axes=c(3,4), col=as.numeric(as.factor(X$ZoogD)))
# dev.off()
# pdf('Fig-PLNPCA.cov-aravo-corPC1-2.pdf')
bestPLNPCA.cov$plot_correlation.circle(axes=c(1,2))
# dev.off()
# pdf('Fig-PLNPCA.cov-aravo-corPC3-4.pdf')
bestPLNPCA.cov$plot_correlation.circle(axes=c(3,4))
# dev.off()

####################################################################
# PLNPCA + cov
PLNPCA.cov.offset = PLNPCA(Y ~ 1 + X$Aspect + X$Slope + X$Form + X$PhysD + X$ZoogD + X$Snow + offset(O),
   Q=Q.list)
save(PLNPCA.cov.offset, file='aravo-PLNPCA.cov.offset.Rdata')
load('aravo-PLNPCA.cov.offset.Rdata')
# pdf('Fig-PLNPCA.cov.offset-aravo-modsel.pdf')
PLNPCA.cov.offset$plot()
# dev.off()
bestPLNPCA.cov.offset = PLNPCA.cov.offset$getModel(which.max(PLNPCA.cov.offset$criteria$R2))
# pdf('Fig-PLNPCA.cov.offset-aravo-invPC1-2.pdf')
bestPLNPCA.cov.offset$plot_individual.map(axes=c(1,2), col=as.numeric(as.factor(X$ZoogD)))
# dev.off()
# pdf('Fig-PLNPCA.cov.offset-aravo-invPC3-4.pdf')
bestPLNPCA.cov.offset$plot_individual.map(axes=c(3,4), col=as.numeric(as.factor(X$ZoogD)))
# dev.off()
# pdf('Fig-PLNPCA.cov.offset-aravo-corPC1-2.pdf')
bestPLNPCA.cov.offset$plot_correlation.circle(axes=c(1,2))
# dev.off()
# pdf('Fig-PLNPCA.cov.offset-aravo-corPC3-4.pdf')
bestPLNPCA.cov.offset$plot_correlation.circle(axes=c(3,4))
# dev.off()
