title h=1.3 'ETGC00 : Estimation de f0 / f par modele logistique';

options linesize=100 pagesize=35;

title2 'Simulation';
data SCORE;
    n = 7000; mu = 2; pas = 0.2;
    do i=1 to n;
        if ranuni(1)<0.2 then do;
            if ranuni(1)<0.5 then do;
                Type = +1;
                Z = mu + normal(1);
            end;
            else do;
                Type = -1;
                Z = -mu + normal(1);
            end;
        end;
        else do;
            Type = 0;
            Z = normal(1);
        end;
        Code = abs(Type);
        Zred = round(Z, pas);
        output;
    end;
    drop mu n pas;
*proc Print data=SCORE;
proc Sort data=SCORE;
    by Code Z;
proc Freq data=SCORE noprint;
    tables Zred/ out=DENSITE;
    by Code;
proc Gplot data=FREQ;
    symbol1 i=sm50 v=none c=black l=1;
    symbol2 i=sm50 v=none c=black l=2;
    plot  Percent*Zred = Code;
run;

title2 'Estimation';
proc Freq data=SCORE noprint;
    tables Zred * Code / out=FREQ;
proc Sort data=FREQ;
     by Zred;
data SCORE0;     set FREQ;     if Code = 0;    rename Count=Count0;
data SCORE1;     set FREQ;     if Code = 1;    rename Count=Count1;
data ESTIM;
    merge SCORE0 SCORE1;
    by Zred;
data ESTIM;
    set ESTIM;
    Pi = Count1 / (Count0 + Count1);
proc Print data=ESTIM;
proc Gplot data=ESTIM;
    symbol1 i=sm50 v=none c=black l=1;
    symbol2 i=sm50 v=none c=black l=2;
    plot  Pi*Zred = Code;
run;
