data PVALUE;
	n = 5000;
	do i=1 to n;
		if ranuni(1) < 0.1 then do;
			X = -log(ranuni(1))/1000;
			Z = 1;
			end;
		else do;
			X = ranuni(1);
			Z = 0;
		end;
		Y = probit(X);
		output;
	end;
	label X = 'p-value';
	label Y = 'probit(p-value)';
	drop i n;
proc Sort data=PVALUE;
	by Z X;
proc Means data=PVALUE;
	by Z;
proc GChart data=PVALUE;
	vbar X;
	by Z;
run; quit;
ods ps file="d:/RECHERCHE/EXPRESSION/Articles/MelangeNonParam/HistoPval.ps";
proc GChart data=PVALUE;
	axis1 label=none;
	vbar X / subgroup=Z nolegend percent maxis=axis1 gaxis=axis1;
run;
ods ps close;
run; quit;
ods ps file="d:/RECHERCHE/EXPRESSION/Articles/MelangeNonParam/HistoProbit.ps";
proc GChart data=PVALUE;
	axis1 label=none;
	vbar Y / subgroup=Z nolegend percent maxis=axis1 gaxis=axis1;
run;  
ods ps close;
run; quit;
